# LatterOS Milestone 20D release-candidate boot menu.
timeout: 3
default_entry: 1
interface_resolution: 1280x800
interface_branding: LatterOS

/LatterOS
    protocol: limine
    path: boot():/boot/kernel
    cmdline: source=installer mode=normal
    module_path: boot():/boot/kernel
    module_string: latteros-installer-kernel
    module_path: boot():/EFI/BOOT/BOOTX64.EFI
    module_string: latteros-installer-bootx64
    resolution: 1280x800x32

/LatterOS Safe Mode
    protocol: limine
    path: boot():/boot/kernel
    cmdline: source=installer mode=safe
    module_path: boot():/boot/kernel
    module_string: latteros-installer-kernel
    module_path: boot():/EFI/BOOT/BOOTX64.EFI
    module_string: latteros-installer-bootx64
    resolution: 1280x800x32

/LatterOS Recovery
    protocol: limine
    path: boot():/boot/kernel
    cmdline: source=installer mode=recovery
    module_path: boot():/boot/kernel
    module_string: latteros-installer-kernel
    module_path: boot():/EFI/BOOT/BOOTX64.EFI
    module_string: latteros-installer-bootx64
    resolution: 1280x800x32

/LatterOS Hardware Test
    protocol: limine
    path: boot():/boot/kernel
    cmdline: source=installer mode=hardware
    module_path: boot():/boot/kernel
    module_string: latteros-installer-kernel
    module_path: boot():/EFI/BOOT/BOOTX64.EFI
    module_string: latteros-installer-bootx64
    resolution: 1280x800x32

/LatterOS Compatibility Mode
    protocol: limine
    path: boot():/boot/kernel
    cmdline: source=installer mode=compatibility
    module_path: boot():/boot/kernel
    module_string: latteros-installer-kernel
    module_path: boot():/EFI/BOOT/BOOTX64.EFI
    module_string: latteros-installer-bootx64
    resolution: 1280x800x32

/LatterOS VirtualBox Mode
    protocol: limine
    path: boot():/boot/kernel
    cmdline: source=installer mode=virtualbox
    module_path: boot():/boot/kernel
    module_string: latteros-installer-kernel
    module_path: boot():/EFI/BOOT/BOOTX64.EFI
    module_string: latteros-installer-bootx64
    resolution: 1280x800x32
