# LatterOS recovery media boot menu.
timeout: 3
default_entry: 1
interface_resolution: 1280x800
interface_branding: LatterOS Recovery

/LatterOS Recovery
    protocol: limine
    path: boot():/boot/kernel
    cmdline: source=recovery-media mode=recovery
    module_path: boot():/boot/kernel
    module_string: latteros-installer-kernel
    module_path: boot():/EFI/BOOT/BOOTX64.EFI
    module_string: latteros-installer-bootx64
    resolution: 1280x800x32

/LatterOS Safe Mode
    protocol: limine
    path: boot():/boot/kernel
    cmdline: source=recovery-media mode=safe
    module_path: boot():/boot/kernel
    module_string: latteros-installer-kernel
    module_path: boot():/EFI/BOOT/BOOTX64.EFI
    module_string: latteros-installer-bootx64
    resolution: 1280x800x32

/LatterOS Normal Boot
    protocol: limine
    path: boot():/boot/kernel
    cmdline: source=recovery-media mode=normal
    module_path: boot():/boot/kernel
    module_string: latteros-installer-kernel
    module_path: boot():/EFI/BOOT/BOOTX64.EFI
    module_string: latteros-installer-bootx64
    resolution: 1280x800x32

/LatterOS Hardware Test
    protocol: limine
    path: boot():/boot/kernel
    cmdline: source=recovery-media mode=hardware
    module_path: boot():/boot/kernel
    module_string: latteros-installer-kernel
    module_path: boot():/EFI/BOOT/BOOTX64.EFI
    module_string: latteros-installer-bootx64
    resolution: 1280x800x32
